### ISSUE TITLE
Feature request - button/option to skip torrent2box

### ISSUE THREAD

**Issue by deathstrikex** [peardropsoftware/torrent2box#4]
Maybe ctrl+shift+click or caps lock on / scoll lock on to skip sending torrent file to box.

Right now right link and save link as works.  Hopefully, there was an option to do it without two clicks.

**Comment by rmuchall** [comment]
Many thanks for your feedback. I have fixed this for the next release (v0.0.10) which has just been submitted to the Chrome Store.
In v0.0.10 you can press CTRL or SHIFT or ALT and this will skip torrent2box.
Thanks!
